

 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.2.1.3")]
 [assembly: AssemblyFileVersion("0.2.1.3")]
